--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: drone; Type: TABLE; Schema: public; Owner: user1
--

CREATE TABLE public.drone (
    id bigint NOT NULL,
    license_plate character varying(255),
    manufacturer character varying(255),
    model character varying(255),
    production_date timestamp without time zone,
    registration_date timestamp without time zone,
    write_off_date timestamp without time zone
);


ALTER TABLE public.drone OWNER TO user1;

--
-- Name: drone_id_seq; Type: SEQUENCE; Schema: public; Owner: user1
--

ALTER TABLE public.drone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: user1
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    system_name character varying(255),
    user_friendly_name character varying(255)
);


ALTER TABLE public.role OWNER TO user1;

--
-- Name: t_order; Type: TABLE; Schema: public; Owner: user1
--

CREATE TABLE public.t_order (
    id bigint NOT NULL,
    date timestamp without time zone,
    departure_address character varying(255),
    destination_address character varying(255),
    drone_id bigint,
    operator_id bigint,
    user_id bigint,
    current_status integer
);


ALTER TABLE public.t_order OWNER TO user1;

--
-- Name: t_order_id_seq; Type: SEQUENCE; Schema: public; Owner: user1
--

ALTER TABLE public.t_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_user; Type: TABLE; Schema: public; Owner: user1
--

CREATE TABLE public.t_user (
    id bigint NOT NULL,
    birthdate character varying(255),
    email_address character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    patronym character varying(255),
    phone_number character varying(255),
    username character varying(255)
);


ALTER TABLE public.t_user OWNER TO user1;

--
-- Name: t_user_id_seq; Type: SEQUENCE; Schema: public; Owner: user1
--

ALTER TABLE public.t_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_roles; Type: TABLE; Schema: public; Owner: user1
--

CREATE TABLE public.users_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.users_roles OWNER TO user1;

--
-- Data for Name: drone; Type: TABLE DATA; Schema: public; Owner: user1
--

COPY public.drone (id, license_plate, manufacturer, model, production_date, registration_date, write_off_date) FROM stdin;
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: user1
--

COPY public.role (id, system_name, user_friendly_name) FROM stdin;
1	ROLE_USER	Пользователь
2	ROLE_ADMIN	Администратор
\.


--
-- Data for Name: t_order; Type: TABLE DATA; Schema: public; Owner: user1
--

COPY public.t_order (id, date, departure_address, destination_address, drone_id, operator_id, user_id, current_status) FROM stdin;
\.


--
-- Data for Name: t_user; Type: TABLE DATA; Schema: public; Owner: user1
--

COPY public.t_user (id, birthdate, email_address, first_name, last_name, password, patronym, phone_number, username) FROM stdin;
1	2000-02-01	ivanov@example.com	Иван	Иванов	$2a$10$M/HiqBf0XWYA8m0c4QGxnOpjPxI84CVlHNSrph.OKj9INvGzknQRu	Иванович	+79991234567	ivanov
3	1976-01-01	admin@example.com	Админ	Админов	$2a$10$4HRUX8Y17QWamJ6NE4Xfe.OrxRJTL.a8P4AHR8JulVNU1kfMqSvpK	Админович	+79091123039	admin
4	1950-01-18	user@example.com	Пётр	Петров	$2a$10$PbUOBooujbzD/vgE5YO0BOH14f6YrMql0Gs9KvOnueWdlWfjsT0C.	Петрович	+79998887766	user
\.


--
-- Data for Name: users_roles; Type: TABLE DATA; Schema: public; Owner: user1
--

COPY public.users_roles (user_id, role_id) FROM stdin;
1	1
3	1
3	2
4	1
\.


--
-- Name: drone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user1
--

SELECT pg_catalog.setval('public.drone_id_seq', 1, false);


--
-- Name: t_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user1
--

SELECT pg_catalog.setval('public.t_order_id_seq', 1, false);


--
-- Name: t_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user1
--

SELECT pg_catalog.setval('public.t_user_id_seq', 4, true);


--
-- Name: drone drone_pkey; Type: CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.drone
    ADD CONSTRAINT drone_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: t_order t_order_pkey; Type: CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.t_order
    ADD CONSTRAINT t_order_pkey PRIMARY KEY (id);


--
-- Name: t_user t_user_pkey; Type: CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.t_user
    ADD CONSTRAINT t_user_pkey PRIMARY KEY (id);


--
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: t_order fk3mff6i118kylaimkccicr0l0d; Type: FK CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.t_order
    ADD CONSTRAINT fk3mff6i118kylaimkccicr0l0d FOREIGN KEY (operator_id) REFERENCES public.t_user(id);


--
-- Name: users_roles fk48qhl0k3dvjwm8v1dg614tlqd; Type: FK CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk48qhl0k3dvjwm8v1dg614tlqd FOREIGN KEY (user_id) REFERENCES public.t_user(id);


--
-- Name: t_order fkgqh46y7g88dieku8p1qpoefwo; Type: FK CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.t_order
    ADD CONSTRAINT fkgqh46y7g88dieku8p1qpoefwo FOREIGN KEY (drone_id) REFERENCES public.drone(id);


--
-- Name: t_order fkho2r4qgj3txpy8964fnla95ub; Type: FK CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.t_order
    ADD CONSTRAINT fkho2r4qgj3txpy8964fnla95ub FOREIGN KEY (user_id) REFERENCES public.t_user(id);


--
-- Name: users_roles fkt4v0rrweyk393bdgt107vdx0x; Type: FK CONSTRAINT; Schema: public; Owner: user1
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkt4v0rrweyk393bdgt107vdx0x FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

